[package]
name = "wasm-flappy-bird"
version = "0.1.0"
authors = ["alexandre <alexandre@senges.ch>"]
edition = "2018"
license-file = "LICENSE"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = { version = "0.2.74", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.24"
js-sys = "0.3.51"
rand = "0.8.3"
getrandom = { version = "0.2.1", features = ["js"] }
neat-gru = "1.1.0"
serde = "1.0.126"
async-trait = "0.1.50"
futures = "0.3.15"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.5", optional = true }

[dependencies.web-sys]
version = "0.3.4"
features = [
    'CanvasRenderingContext2d',
    'Document',
    'Element',
    'EventListener',
    'EventTarget',
    'KeyboardEvent',
    'HtmlCanvasElement',
    'HtmlInputElement',
    'MouseEvent',
    'Window',
]

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
